FROM node:10.26.1

WORKDIR /usr/src/app/

RUN npm i -g \
    typescript \
    ts-loader \
    webpack \
    webpack-cli \
    webpack-dev-server \
    eslint-loader \
    vue-loader \
    vue-template-compiler \
    vue-router \
    --save-dev
