version: '3'

services:
  # node:
  #   build:
  #     context: ./node
  #     dockerfile: Dockerfile
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./src:/usr/src/app
  #   tty: true

  nginx:
    image: nginx:1.21.5
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - 6603:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=gizlog
      - LANG=C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  db:
